version: "3.8"
services:
  mongo1:
    image: mongo:6.0
    command: ["--replSet", "rs0", "--bind_ip_all", "--port", "27017"]
    ports:
      - 27017:27017
    extra_hosts:
      - "host.docker.internal:host-gateway"
    healthcheck:
      test: echo "try { rs.status() } catch (err) { rs.initiate({_id:'rs0',members:[{_id:0,host:'mongo1:27017',priority:1}]}) }" | mongosh --port 27017 --quiet
      interval: 5s
      timeout: 30s
      start_period: 0s
      start_interval: 1s
      retries: 30
    volumes:
      - "mongo1_data:/data/db"
      - "mongo1_config:/data/configdb"
    networks:
      - mongo-network
  # redis:
  #   container_name: redis
  #   image: redis:latest
  #   volumes:
  #     - redis:/data/redis
  #   ports:
  #     - 6379:6379
  # rabbitmq:
  #   container_name: rabbitmq
  #   image: rabbitmq:3.8.0-management
  #   volumes:
  #     - rabbitmq:/var/lib/rabbitmq
  #   ports:
  #     - 5672:5672
  #     - 15672:15672

volumes:
  mongo1_data:
  mongo1_config:
  # redis:
  # rabbitmq:

networks:
  mongo-network:
